repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        exclude: (^data/)
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3.11
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: (^data/)
        name: isort (python)
        language_version: python3.11

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        exclude: (^data/)
        language_version: python3.11
        args: [--max-line-length=88]

-   repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]
        files: .
-   repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score,
          "--generated-members='torch.*'", # pytorch to look for both torch and torch._C
        ]
